/* IAOps LATAM — catálogo de clases (fuente única del área de miembro).
   Orden = orden de grabación (docs/iaops/temario-iaops.md §5.1).
   video: "" = aún no grabada (el player muestra el estado 📅 eta). */
window.IAOPS_CATALOG = [
  { id: "a1", t: "Qué es IAOps (y por qué en EE.UU. lo llaman AI SRE)", cat: "FUNDAMENTOS", lvl: "BÁSICO", min: 25, free: true, eta: "septiembre", video: "",
    d: "El mapa mental del campo — del datacenter a los agentes, y el término dominado.",
    m: "Escribe qué 3 tareas de tu operación delegarías primero y compártelo en la comunidad." },
  { id: "a2", t: "La frontera de delegación: qué firma un humano", cat: "FUNDAMENTOS", lvl: "BÁSICO", min: 25, free: true, eta: "septiembre", video: "",
    d: "Reversible se delega, irreversible se firma — terminas con TU política escrita.",
    m: "Dibuja tu frontera de delegación con la plantilla incluida y publícala en la comunidad." },
  { id: "a3", t: "Tu primer agente ejecutando una tarea real", cat: "AGENTES", lvl: "BÁSICO", min: 30, free: true, eta: "septiembre", video: "",
    d: "Demo en vivo: un agente inventaría una cuenta AWS y reporta con evidencia.",
    m: "Configura tu agente con permisos de solo lectura y pídele el inventario de tu cuenta. Comparte el resultado con #primer-agente." },
  { id: "a4", t: "Claude Code para operar tu nube: setup completo", cat: "AGENTES", lvl: "BÁSICO", min: 35, free: false, eta: "octubre", video: "",
    d: "Instalación, perfiles de solo lectura y las reglas de la casa — tu entorno agéntico listo.",
    m: "Deja tu entorno agéntico funcionando y corre tu primera auditoría de seguridad básica." },
  { id: "a5", t: "De clicks a Terraform con un agente", cat: "CÓDIGO", lvl: "BÁSICO", min: 35, free: false, eta: "octubre", video: "",
    d: "El agente escribe el código de un recurso que ya tienes; tú revisas el plan.",
    m: "Migra tu primer recurso click-ops a código con tu agente (terraform plan como contrato)." },
  { id: "a6", t: "Pipeline OIDC: deploys sin llaves y sin consola", cat: "CÓDIGO", lvl: "INTERMEDIO", min: 35, free: false, eta: "octubre", video: "",
    d: "GitHub Actions asume un rol — push → plan → apply sin un secreto guardado.",
    m: "Haz que tu repo despliegue a tu cuenta sin un solo secreto guardado." },
  { id: "a7", t: "Audita tu factura AWS con un agente (FinOps en 30 min)", cat: "FINOPS", lvl: "BÁSICO", min: 30, free: false, eta: "octubre", video: "",
    d: "Huérfanos, tamaños, horarios y storage — el reporte de ahorro de TU cuenta.",
    m: "Audita tu cuenta (o la de tu empresa, con permiso) y cuantifica el hallazgo." },
  { id: "a8", t: "El runbook delegable: verificar → backup → cambiar → validar", cat: "OPERACIÓN", lvl: "INTERMEDIO", min: 30, free: false, eta: "noviembre", video: "",
    d: "El patrón universal de los cambios seguros, ejecutado por un agente con puntos de firma.",
    m: "Convierte un procedimiento tuyo al patrón verificar→backup→cambiar→validar y delégalo." },
  { id: "a9", t: "Cambio de DNS en producción con firma (caso real)", cat: "OPERACIÓN", lvl: "INTERMEDIO", min: 30, free: false, eta: "noviembre", video: "",
    d: "Anatomía de un cutover real: dominio vivo, cero downtime, rollback diseñado antes.",
    m: "Simula un cutover en tu lab (hosted zone de prueba) con plan de rollback." },
  { id: "a10", t: "Permisos mínimos: IAM para agentes", cat: "GUARDRAILS", lvl: "INTERMEDIO", min: 30, free: false, eta: "noviembre", video: "",
    d: "Por qué el agente no usa tu admin — diseño de un rol scoped, con caso real.",
    m: "Crea el rol de tu agente con permisos mínimos (solo-lectura → reversible → proponer)." },
  { id: "a11", t: "Primera respuesta a incidentes con agentes", cat: "INCIDENTES", lvl: "INTERMEDIO", min: 35, free: false, eta: "diciembre", video: "",
    d: "Los primeros 5 minutos: el agente recolecta evidencia mientras tú piensas.",
    m: "Simulacro: rompe algo en tu lab y dirige el diagnóstico con hipótesis rankeadas." },
  { id: "a12", t: "AWS DevOps Agent y Azure SRE Agent: qué son y cómo dirigirlos", cat: "AGENTES", lvl: "INTERMEDIO", min: 35, free: false, eta: "diciembre", video: "",
    d: "Lo que los hyperscalers venden — y cómo gobernarlo. First-mover en español.",
    m: "Activa el agente de tu nube en modo recomendación y evalúa su primer diagnóstico." }
];
